### ISSUE TITLE
GPS positioning, not very precise 

### ISSUE THREAD

**Issue by Slayingripper** [dj1an/Cubecell_LoRa_APRS_Tracker#1]
I've let the board run for a while at a stationary position. It seems to move about, I assume this might be a GPS issue, but I have a feeling it might be the conversion from GPS Coordinates to APRS packet format. It's not TOO far off but will test this further.

![image](https://user-images.githubusercontent.com/11594874/147502697-103b45db-801c-453b-a0a8-1a70c5f2a57a.png)

**Comment by dj1an** [comment]
I have added some kind of position Validation to the Code.
Maybe this helps to stop the jumping positions?

We could further check for a low hdop Value.
But with bad GPS Rx conditions this would lead to no Beacon Tx at all. 
Please test the updated code and let me know.

**Comment by Slayingripper** [comment]
After leaving the tracker and the IGATE for a few hours, it seems like the tracking now is a bit more precise with the new code. 
![image](https://user-images.githubusercontent.com/11594874/147564855-2151dfd0-ff25-4a65-a518-b1332c392435.png)
